# Generated by Django 4.0.3 on 2022-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0005_remove_orderplaced_address_remove_orderplaced_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_status',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
