# Generated by Django 4.0.3 on 2022-04-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0006_alter_orderplaced_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_status',
            field=models.IntegerField(default=False),
        ),
    ]
