# Generated by Django 4.0.3 on 2022-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0007_alter_orderplaced_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField()),
                ('Phone_no', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('date', models.DateField()),
                ('delivery_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
