# Generated by Django 4.0.3 on 2022-04-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Phone_no',
        ),
    ]
