# Generated by Django 4.0.3 on 2022-04-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0009_remove_payment_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
