# Generated by Django 4.0.3 on 2022-04-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0012_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shipping_address',
            field=models.TextField(null=True),
        ),
    ]
