# Generated by Django 4.0.3 on 2022-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0013_alter_payment_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='delivery_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
